{{ if .Values.nodeAnalyzer.cspmAnalyzer.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nodeAnalyzer.name" . }}-cspm-analyzer
  labels:
{{ include "nodeAnalyzer.labels" . | indent 4 }}
data:
  environment: "{{ .Values.nodeAnalyzer.cspmAnalyzer.environemt | default "PRODUCTION" }}"
  {{- if .Values.nodeAnalyzer.cspmAnalyzer.externalNatsUrl }}
  external_nats_url: {{ .Values.nodeAnalyzer.cspmAnalyzer.externalNatsUrl }}
  {{- end -}}
{{- end -}}
