{{ if .Values.nodeAnalyzer.cspmAnalyzer.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sysdig.fullname" . }}-cspm-analyzer
  labels:
{{ include "sysdig.labels" . | indent 4 }}
data:
  environment: "{{ .Values.nodeAnalyzer.cspmAnalyzer.environemt | default "PRODUCTION" }}"
  external_nats_url: {{ include "sysdig.nodeAnalyzer.natsUrl" . }}
  cluster_name: {{ required "A valid .Values.clusterName is required" .Values.clusterName }}
  agent_app_name: {{ include "sysdig.name" . }}-node-analyzer
{{- end -}}